{{- if .Values.sourceController.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller
  name: {{ .Values.sourceController.deploymentName }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{ .Values.sourceController.deploymentName }}
  type: ClusterIP
{{- end }}