{{- if .Values.kustomization.enabled }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-releases
  namespace: {{ .Values.kustomization.namespace }}
spec:
  interval: {{ .Values.kustomization.interval }}
  sourceRef:
    kind: GitRepository
    name: helm-releases
  path: {{ .Values.kustomization.path }}
  prune: {{ .Values.kustomization.prune }}
{{- end }}